"""build_targeting_map_slide.py -- add the no-photo "map" variant of the
avails/targeting template slide to a master deck (roadmap section E, item 4:
give the targeting map a slide with no stock photo competing with it).

    python build_targeting_map_slide.py <deck.pptx> -o <output.pptx>

What it does, precisely:

1. Finds the avails/targeting template slide -- the one whose table's
   header row starts "Audience" (same lookup assembly._find_table_shape +
   header check uses everywhere else in this codebase). Never by slide
   number, which drifts every time the deck is edited.
2. Duplicates it (assembly.duplicate_slide) immediately after the
   original -- cosmetic placement only; slide_map resolves both by
   condition_key, never by position.
3. On the duplicate, strips two shapes:
   - The full-bleed background photo: a PICTURE covering (within 5%)
     the entire slide. This is what makes the map's backdrop the deck's
     own dark theme gradient instead of a stock photo -- the slide
     MASTER carries that same gradient underneath everything, and it
     shows through the template's translucent overlay rectangle once the
     opaque photo on top of it is gone. No other change needed for that.
   - Any remaining PICTURE on the slide whose position and size closely
     match a PICTURE on the slide's own MASTER (within 0.05in): the
     master already draws its own copy of that image on every slide, and
     it's normally hidden behind the opaque background photo -- once
     that photo is gone, the slide's own copy just doubles up with the
     master's, which is what a smeared "PREMION" wordmark in the render
     turned out to be. Detected by geometry, not by name ("Picture 71"
     happened to be its name in the deck this was built against, but a
     shape's autogenerated name isn't guaranteed stable across exports).
4. Tags the duplicate's notes with the map-variant condition_key
   (`key: targeting_avails_template:map`, see assembly.TARGETING_AVAILS_MAP_KEY)
   so slide_map.py resolves it as distinct from the standard template --
   they're token-identical otherwise, so only the notes key can tell them
   apart, the same mechanism the Total TV variants use.

Verifies the result with package_check.check_package before reporting
success. Never writes in place -- same discipline as tag_deck_keys.py.
"""
import argparse
import sys
from pathlib import Path

from pptx import Presentation
from pptx.util import Emu

import assembly
import package_check
import tag_deck_keys

MAP_VARIANT_KEY = assembly.TARGETING_AVAILS_MAP_KEY
FULL_BLEED_COVERAGE = 0.95
# Same image, not necessarily pixel-identical placement: measured against
# two real decks, a slide's own wordmark copy and the master's sat 0.2in
# apart horizontally (design nudge, not drift) while matching in size to
# within a few EMU -- so size is the tight signal here, position only
# loose enough to mean "the same corner of the slide," not "the same
# point."
WORDMARK_SIZE_TOLERANCE = Emu(int(0.02 * 914400))
WORDMARK_POSITION_TOLERANCE = Emu(int(0.4 * 914400))


def find_avails_slide(prs):
    for index, slide in enumerate(prs.slides):
        table_shape = assembly._find_table_shape(slide)
        if table_shape is None or len(table_shape.table.rows) < 1:
            continue
        header0 = table_shape.table.rows[0].cells[0].text_frame.text.strip().lower()
        if header0 == "audience":
            return index, slide
    return None, None


def is_full_bleed(shape, slide_width, slide_height):
    if shape.shape_type != 13 or shape.left is None:  # 13 == MSO_SHAPE_TYPE.PICTURE
        return False
    return (shape.width >= slide_width * FULL_BLEED_COVERAGE
            and shape.height >= slide_height * FULL_BLEED_COVERAGE
            and abs(shape.left) <= slide_width * (1 - FULL_BLEED_COVERAGE)
            and abs(shape.top) <= slide_height * (1 - FULL_BLEED_COVERAGE))


def close(a, b, tolerance):
    return abs(a - b) <= tolerance


def matches_master_picture(shape, master_pictures):
    if shape.shape_type != 13 or shape.left is None:
        return False
    for mp in master_pictures:
        if (close(shape.width, mp.width, WORDMARK_SIZE_TOLERANCE)
                and close(shape.height, mp.height, WORDMARK_SIZE_TOLERANCE)
                and close(shape.left, mp.left, WORDMARK_POSITION_TOLERANCE)
                and close(shape.top, mp.top, WORDMARK_POSITION_TOLERANCE)):
            return True
    return False


def build(src_path, dst_path):
    prs = Presentation(src_path)
    slide_width, slide_height = prs.slide_width, prs.slide_height

    index, source_slide = find_avails_slide(prs)
    if source_slide is None:
        print("Could not find the avails/targeting template slide "
              "(no table with 'Audience' as its first header cell).")
        return False
    print(f"Found the avails/targeting template at slide {index + 1} of {len(prs.slides)}.")

    master_pictures = [s for s in source_slide.slide_layout.slide_master.shapes
                       if s.shape_type == 13]

    new_slide = assembly.duplicate_slide(prs, source_slide, insert_at=index + 1)

    removed = []
    for shape in list(new_slide.shapes):
        if is_full_bleed(shape, slide_width, slide_height):
            removed.append(("full-bleed background photo", shape.name,
                            (shape.left, shape.top, shape.width, shape.height)))
            shape._element.getparent().remove(shape._element)
            continue
        if matches_master_picture(shape, master_pictures):
            removed.append(("redundant master-wordmark duplicate", shape.name,
                            (shape.left, shape.top, shape.width, shape.height)))
            shape._element.getparent().remove(shape._element)

    if not any(r[0] == "full-bleed background photo" for r in removed):
        print("  WARNING: no full-bleed background photo was found on the source slide -- "
              "the map variant may still show a stock image. Check the slide by hand.")

    for kind, name, geom in removed:
        left, top, width, height = (v / 914400 for v in geom)
        print(f"  removed {kind}: {name!r} at ({left:.2f}in, {top:.2f}in), "
              f"{width:.2f}in x {height:.2f}in")

    tag_deck_keys.write_notes_key(new_slide, MAP_VARIANT_KEY)
    print(f"  tagged new slide {index + 2} with: key: {MAP_VARIANT_KEY}")

    prs.save(dst_path)
    print(f"Saved {dst_path}")

    problems = package_check.check_package(dst_path)
    if problems:
        print(f"  FAIL -- package_check found {len(problems)} problem(s):")
        for p in problems[:10]:
            print(f"    {p}")
        return False
    print("  package_check: OK")
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("source", help="deck to add the map-variant slide to")
    parser.add_argument("-o", "--output", help="output path (default: <source>_with_map_slide.pptx)")
    args = parser.parse_args()

    source = Path(args.source)
    if not source.exists():
        print(f"No such deck: {source}")
        return 1
    output = Path(args.output) if args.output else source.with_name(
        source.stem + "_with_map_slide.pptx")

    ok = build(str(source), str(output))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
